site_name: Geoweaver

docs_dir: "docs"

theme:
  name: readthedocs
  font:
    text: Roboto
  logo: 'img/header.png'

nav:
  - Home: index.md
  - Installation: install.md
  - Java 17 migration: java17-migration.md
  - Upgrading: upgrade.md
  - Hosts: host.md
  - Processes: process.md
  - Workflows: workflow.md
  - Environment selection: environment-selection.md
  - Database: database-configuration.md
  - HTTP proxy: http-proxy.md
  - Logging: logging.md
  - Release process: release_upgrade.md
  - Authors: authors.md
