name: Commit Workflow

on:
  push:
    branches:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      - name: Run Tests
        run: |
          mvn test jacoco:report
        working-directory: ${{ github.workspace }}

      - name: Check If All Tests Pass
        run: |
          if [ $? -eq 0 ]; then
            echo "All tests passed successfully."
          else
            echo "Tests failed."
            exit 1  # Exit with an error code to stop the workflow
          fi

      - name: Save Geoweaver JaCoCo HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: geoweaver-jacoco-coverage-report-tests-${{ github.run_id }}-${{ github.run_attempt }}
          path: target/site/jacoco

  test-mysql:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: geoweaver
          MYSQL_DATABASE: geoweaver
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h localhost" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64

    - name: Create geoweaver directory and application.properties
      run: |
        mkdir -p ~/geoweaver
        echo "spring.datasource.url=jdbc:mysql://localhost:3306/geoweaver" >> ~/geoweaver/application.properties
        echo "spring.datasource.username=root" >> ~/geoweaver/application.properties
        echo "spring.datasource.password=geoweaver" >> ~/geoweaver/application.properties
        echo "spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver" >> ~/geoweaver/application.properties
        echo "spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect" >> ~/geoweaver/application.properties

    - name: Run Tests
      run: |
        mvn test jacoco:report
      working-directory: ${{ github.workspace }}

    - name: Check If All Tests Pass
      run: |
        if [ $? -eq 0 ]; then
          echo "All tests passed successfully."
        else
          echo "Tests failed."
          exit 1  # Exit with an error code to stop the workflow
        fi

    - name: Save Geoweaver JaCoCo HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: geoweaver-jacoco-coverage-report-mysql-${{ github.run_id }}-${{ github.run_attempt }}
        path: target/site/jacoco

  test-postgresql:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: geoweaver
          POSTGRES_DB: geoweaver
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64

    - name: Create geoweaver directory and application.properties
      run: |
        mkdir -p ~/geoweaver
        echo "spring.datasource.url=jdbc:postgresql://localhost:5432/geoweaver" >> ~/geoweaver/application.properties
        echo "spring.datasource.username=postgres" >> ~/geoweaver/application.properties
        echo "spring.datasource.password=geoweaver" >> ~/geoweaver/application.properties
        echo "spring.datasource.driver-class-name=org.postgresql.Driver" >> ~/geoweaver/application.properties
        echo "spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect" >> ~/geoweaver/application.properties

    - name: Run Tests
      run: |
        mvn test jacoco:report
      working-directory: ${{ github.workspace }}

    - name: Check If All Tests Pass
      run: |
        if [ $? -eq 0 ]; then
          echo "All tests passed successfully."
        else
          echo "Tests failed."
          exit 1  # Exit with an error code to stop the workflow
        fi

    - name: Save Geoweaver JaCoCo HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: geoweaver-jacoco-coverage-postgresql-report-${{ github.run_id }}-${{ github.run_attempt }}
        path: target/site/jacoco
