name: Commit Workflow

on:
  push:
    branches:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      - name: Run Tests
        run: |
          mvn test jacoco:report
        working-directory: ${{ github.workspace }}

      - name: Check If All Tests Pass
        run: |
          if [ $? -eq 0 ]; then
            echo "All tests passed successfully."
          else
            echo "Tests failed."
            exit 1  # Exit with an error code to stop the workflow
          fi

      - name: Save Geoweaver JaCoCo HTML Report
        uses: actions/upload-artifact@v2
        with:
          name: geoweaver-jacoco-coverage-report
          path: target/site/jacoco
